"""add deleted_at to agent_devices and node_meta JSON to audit_log for soft-delete audit context

Revision ID: 5a01a50ef701
Revises: 68d67bfc6697
Create Date: 2026-04-28 13:08:15.934093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a01a50ef701'
down_revision: Union[str, Sequence[str], None] = '68d67bfc6697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_devices', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_agent_devices_deleted_at'), 'agent_devices', ['deleted_at'], unique=False)
    op.add_column('audit_log', sa.Column('node_meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'node_meta')
    op.drop_index(op.f('ix_agent_devices_deleted_at'), table_name='agent_devices')
    op.drop_column('agent_devices', 'deleted_at')
    # ### end Alembic commands ###
